/** LEIA-ME de 3 passos (T6 — entrega Win+Mac offline sem medo de atualizar).
 * Fonte única: `scripts/build.ts` gera `dist/LEIA-ME.txt` a partir daqui,
 * e o teste `tests/t6.test.ts` trava o conteúdo mínimo. */
export function buildLeiaMe(version: string): string {
  return [
    `Gestor de Tráfego Pago v${version} — como abrir (3 passos, 100% offline)`,
    ``,
    `Sem instalar nada: sem Node, sem banco, sem internet. Funciona offline.`,
    `Valores em R$ no formato brasileiro (aceita 4,18 e 4.18).`,
    ``,
    `== Windows (GestorTrafego.exe) ==`,
    `1. Dê dois cliques em GestorTrafego.exe.`,
    `2. Se o Windows mostrar "O Windows protegeu o computador" (programa sem`,
    `   assinatura no v1 — SmartScreen), clique em "Mais informações" e depois`,
    `   em "Executar assim mesmo".`,
    `3. O navegador abre sozinho no painel. Se o programa já estiver aberto,`,
    `   clicar de novo só abre o navegador (não duplica o servidor).`,
    ``,
    `== Mac (GestorTrafego-macos-arm64 ou -x64) ==`,
    `1. Dê dois cliques no executável do seu Mac (arm64 = Apple Silicon, x64 = Intel).`,
    `2. Se o macOS bloquear (Gatekeeper, programa sem assinatura no v1):`,
    `   clique com o botão direito no arquivo e escolha "Abrir" (e confirme`,
    `   em "Abrir" de novo). Se precisar: chmod +x no Terminal.`,
    `3. O navegador abre sozinho no painel. Se o programa já estiver aberto,`,
    `   clicar de novo só abre o navegador (não duplica o servidor).`,
    ``,
    `Onde ficam os dados (fora do executável — trocar o exe não apaga nada):`,
    `- Windows: %APPDATA%\\GestorTrafego\\gestor.db`,
    `- Mac: ~/Library/Application Support/GestorTrafego/gestor.db`,
    `- Backups: pasta "backups" ao lado do banco (30 últimos, um por dia).`,
    ``,
    `Para atualizar sem medo: feche o programa, troque SÓ o executável pelo`,
    `novo e abra de novo. Ao abrir, o app faz backup-antes-de-migrar`,
    `automaticamente e migra o banco sozinho — nada se perde.`,
    `Para trocar de computador, feche o programa antes de copiar a pasta.`,
    ``,
  ].join("\n");
}
